### PR TITLE
 Adding cosmos/mongo-db simple with no failover deployment and single cluster sample env.

### PR DESCRIPTION
**Pull request by mtarng**

### CODE REVIEW

**Comment by mtarng** [comment]
Still need to add integration test.

**Comment by jmspring** [comment]
Code as is looks good, still need tests which will require another review pass.

**Comment by mtarng** [comment]
@jmspring ready for full review. I had some trouble trying to connect to the CosmosDB through terratest, but since there's no azure module yet, I'm just doing a simple check through az cli.

**Comment by NathanielRose** [comment]
Your test deploys an AKS cluster from azure single key vault environment, is this needed. Also Jim an I need to decrease the build time for integration test validation so this will be merged when we can parallelize testing in bedrock.

**Comment by jmspring** [comment]
@NathanielRose @mtarng - for now, I will disable the test, merge, and we can re-enable tests when we get the parallelizing done

**Comment by mtarng** [comment]
Sounds good. I think the source path needs to be changed prior to merge too.

**Comment by jmspring** [comment]
@mtarng - I agree with Nate, can we just do the Cosmos test?  No need for the cluster deployment at the moment.

**Comment by mtarng** [comment]
@jmspring Sure, should i change the environment to just be a cosmos deploy, since it's separate from the cluster anyways? The cosmos db isn't coupled to a cluster in any way.

**Comment by jmspring** [comment]
I think it makes sense, but let's open an issue for that to track it rather than addressing now.

**Pull request merged**
