### PR TITLE
Cluster doc update (including one variable name change)

### PR DESCRIPTION
**Pull request by day-jeff**
- Refactor cluster README.md to add summary and make steps more sequential. 
- Tweak text to improve understanding. 
- Move subscription, tenant and service principle into templates/variables so there is no dependency on env vars. 
- Rename gitops_url to gitops_ssh_url, as it this name makes clarifies that the ssh version of the url should be used.

### CODE REVIEW

**Comment by timfpark** [comment]
Looks great to me - two questions:
1. Should we add the service principal, subscription_id, and tenant_id variables to `terraform.tfvars` to signal that you need to set them?
2. If #1, we should also delete setting the environmental variables we call for in the cluster creation docs?

**Comment by day-jeff** [comment]
1. Yes! I had done so in my local file, but I think the file is (correctly) in .gitignore, so my generic commit of all files didn’t include it. Will fix that.
2. I thought I had deleted the env vars reference. Will look again.

Good catches. Thx.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by day-jeff** [comment]
Fixed both issues.

**Comment by timfpark** [comment]
It looks like there are a couple of small errors (missing variables etc.) in the PR per the CI/CD build failure.  I will take over the PR from here and fix these.

**Comment by day-jeff** [comment]
Sorry

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by timfpark** [comment]
Closing this PR and continuing work on https://github.com/Microsoft/bedrock/pull/135

**Pull request closed without merging**
